{{ '{{- if .Values.externalSecrets.enabled }}' }}
{{ '{{- if eq .Values.p6m.cloud "azure" }}' }}
# An AzureSecretStore is used to integrate with an existing Azure KeyVault.
# The AzureSecretStore will create a workload identity (ie. managed identity), assign RBAC roles
# for the workload identity to the specified keyvault, and create an ESO SecretStore to finish up
# the integration.
# The keyvault should be in the same resource group as the AKS cluster.
apiVersion: secrets.p6m.dev/v1alpha1
kind: AzureSecretStore
metadata:
  name: "{{ '{{ .Release.Name }}' }}"
spec:
  parameters:
    vaultName: "{{ '{{ .Values.externalSecrets.storeName }}' }}"
    enableAccessManagement: true
{{ '{{- end }}' }}
{{ '{{- if eq .Values.p6m.cloud "aws" }}' }}
# An AwsSecretStore is used to integrate with AWS SecretsManager.
# The AwsSecretStore will create an IRSA role, assign IAM policies to the role,
#  and create an ESO SecretStore to finish up the integration.
# The secrets should be created in the same region as the EKS cluster.
apiVersion: secrets.p6m.dev/v1alpha1
kind: AwsSecretStore
metadata:
  name: "{{ '{{ .Release.Name }}' }}"
spec:
  parameters:
    region: "{{ '{{ .Values.p6m.cluster.aws.region }}' }}'
    enableAccessManagement: true
{{ '{{- end }}' }}

# ExternalSecrets
{{ '{{- range .Values.externalSecrets.secrets }}' }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    p6m.dev/shared: "false"
    {{ '{{- include "platform.labels" $ | nindent 4 }}' }}
  name: "{{ '{{ $.Release.Name }}' }}-{{ '{{ .target | default .name }}' }}"
spec:
  {{ '{{- if eq (.format | default "json") "raw" }}' }}
  data:
    - secretKey: value
      remoteRef:
        key: "{{ '{{ .name }}' }}"
  {{ '{{- end }}' }}
  {{ '{{- if eq (.format | default "json") "json" }}' }}
  dataFrom:
    - extract:
        key: "{{ '{{ .name }}' }}"
  {{ '{{- end }}' }}
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: "{{ '{{ $.Release.Name }}' }}"
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: "{{ '{{ .target | default .name }}' }}"
{{ '{{- end }}' }}
{{ '{{- end }}' }}
