{{ '{{- if .Values.externalSecrets.enabled }}' }}
{{ '{{- if eq .Values.p6m.cloud "azure" }}' }}
apiVersion: secrets.p6m.dev/v1alpha1
kind: AzureSecretStore
metadata:
  name: "{{ '{{ .Release.Name }}' }}"
spec:
  parameters:
    {{ '{{- .Values.externalSecrets.storeConfig | toYaml | nindent 4 }}' }}
{{ '{{- end }}' }}
{{ '{{- if eq .Values.p6m.cloud "aws" }}' }}
apiVersion: secrets.p6m.dev/v1alpha1
kind: AwsSecretStore
metadata:
  name: "{{ '{{ .Release.Name }}' }}"
spec:
  parameters:
    {{ '{{- .Values.externalSecrets.storeConfig | toYaml | nindent 4 }}' }}
{{ '{{- end }}' }}

# ExternalSecrets
{{ '{{- range .Values.externalSecrets.secrets }}' }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    p6m.dev/shared: "false"
    {{ '{{- include "platform.labels" $ | nindent 4 }}' }}
  name: "{{ '{{ $.Release.Name }}' }}-{{ '{{ .target | default .name }}' }}"
spec:
  {{ '{{- if eq (.format | default "json") "raw" }}' }}
  data:
    - secretKey: value
      remoteRef:
        key: "{{ '{{ .name }}' }}"
  {{ '{{- end }}' }}
  {{ '{{- if eq (.format | default "json") "json" }}' }}
  dataFrom:
    - extract:
        key: "{{ '{{ .name }}' }}"
  {{ '{{- end }}' }}
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: "{{ '{{ $.Release.Name }}' }}"
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: "{{ '{{ .target | default .name }}' }}"
{{ '{{- end }}' }}
{{ '{{- end }}' }}
