load('ext://helm_resource', 'helm_resource', 'helm_repo')

helm_resource(
    name='this',
    chart='.',
    release_name='{{ project-name }}',
    namespace='{{ wrapped-chart }}',
    flags=[
        '--create-namespace',
        '--values', 'tilt-values.yaml',
    ],
    deps=[
        'tilt-values.yaml',
        'values.yaml',
        'Chart.yaml',
        '.helmignore',
        # Directories
        'templates',
        'charts',
    ],
)

