externalSecrets:
  enabled: false
  storeConfig: {}
  secrets: []
  certificateStoreConfig: {}
  certificates: []

{{ wrapped-chart }}: {}

gatewayApi:
  enabled: false
  gateway:
    create: false
    # name: ''
    # namespace: ''
    # className: ''
    sectionName: https

